name: PR Merged to Develop Event

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - dev

jobs:
  trigger-release-preview:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
          
      - name: Check for changesets
        id: check
        run: |
          # Check if there are any changesets
          CHANGESET_COUNT=0
          
          if [ -d ".changeset" ]; then
            # Count markdown files (excluding README.md)
            for file in .changeset/*.md; do
              if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
                CHANGESET_COUNT=$((CHANGESET_COUNT + 1))
              fi
            done
          fi
          
          echo "changeset_count=$CHANGESET_COUNT" >> $GITHUB_OUTPUT
          
          if [ $CHANGESET_COUNT -gt 0 ]; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
            echo "✅ Found $CHANGESET_COUNT changeset(s)"
          else
            echo "has_changesets=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changesets found"
          fi
          
      - name: Post merge notification
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available for consistency
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const changesetCount = '${{ steps.check.outputs.changeset_count }}';
            const hasChangesets = '${{ steps.check.outputs.has_changesets }}' === 'true';
            
            let message = `## 🎉 Pull Request Merged!
            
            **PR #${pr.number}** has been successfully merged into \`${pr.base.ref}\`.
            `;
            
            if (hasChangesets) {
              message += `
              ### 📦 Release Status
              Found **${changesetCount} changeset(s)** ready for release.
              
              Let me show you what will be included in the next release...`;
            } else {
              message += `
              ### ℹ️ No Changesets Found
              This PR doesn't include any changesets. No version bump will occur.`;
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });
            
      - name: Trigger release preview
        if: steps.check.outputs.has_changesets == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Wait a moment for the notification to be posted
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            // Post the start release preview command
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '/start release --preview'
            });
            
            console.log(`✅ Triggered /start release --preview for merged PR #${pr.number}`);