# 默认分支保护规则
# 适用于 feature/*, fix/*, docs/* 等开发分支
name: default
pattern: "*"  # 匹配所有分支

# 仅对特定模式应用
apply_to:
  - "feature/*"
  - "fix/*"
  - "docs/*"
  - "chore/*"
  - "refactor/*"
  - "test/*"
  - "style/*"
  - "perf/*"

# 排除的分支（不应用这些规则）
exclude:
  - main
  - master
  - develop
  - dev
  - staging
  - production
  - "release/*"
  - "hotfix/*"

protection_rules:
  # ==================
  # 基础设置（宽松）
  # ==================
  require_pull_request_reviews:
    enabled: false                           # 不强制 PR 审核
    
  # ==================
  # 状态检查（可选）
  # ==================
  required_status_checks:
    enabled: false                           # 不强制状态检查
    contexts: []                            # 可选的检查项
      
  # ==================
  # 合并设置
  # ==================
  require_linear_history: false             # 不要求线性历史
  allow_squash_merge: true                  # 允许所有合并方式
  allow_merge_commit: true                  
  allow_rebase_merge: true                  
  allow_auto_merge: false                   # 不允许自动合并
  delete_branch_on_merge: true              # 合并后自动删除
  
  # ==================
  # 推送限制（开放）
  # ==================
  restrict_pushes:
    enabled: false                          # 不限制推送
    
  # ==================
  # 其他保护
  # ==================
  allow_force_pushes: true                  # 允许强制推送（开发分支）
  allow_deletions: true                     # 允许删除分支
  lock_branch: false                        
  require_conversation_resolution: false    
  require_deployments: false                

# ==================
# 分支管理规则
# ==================
branch_management:
  # 命名规范
  naming_convention:
    pattern: "^(feature|fix|docs|chore|refactor|test|style|perf)/[a-z0-9-]+$"
    examples:
      - "feature/user-login"
      - "fix/memory-leak"
      - "docs/api-guide"
      - "chore/update-deps"
    error_message: |
      分支名不符合规范！
      请使用: {type}/{description}
      其中 type 为: feature|fix|docs|chore|refactor|test|style|perf
      description 使用小写字母、数字和连字符
  
  # 生命周期管理
  lifecycle:
    max_age_days: 30                        # 最长存活时间
    stale_warning_days: 21                  # 过期警告时间
    auto_close_days: 60                     # 自动关闭时间
    
  # 合并规则
  merge_rules:
    allowed_targets:                        # 允许合并到的分支
      "feature/*": ["develop"]
      "fix/*": ["develop", "main"]          # fix 可以合并到 main（hotfix）
      "docs/*": ["develop", "main"]         # 文档可以直接到 main
      "chore/*": ["develop"]
      "refactor/*": ["develop"]
      "test/*": ["develop"]
      "style/*": ["develop"]
      "perf/*": ["develop"]
    
    forbidden_targets:                      # 禁止合并到的分支
      "*": ["feature/*", "fix/*"]           # 不能合并到其他功能分支
      
# ==================
# 自动化规则
# ==================
automation:
  # PR 创建时
  on_pr_created:
    # 自动分配
    auto_assign:
      enabled: true
      reviewers: 1                          # 自动分配 1 个审核者
      from_team: ["developers"]
      exclude_author: true
      
    # 自动标签
    auto_label:
      by_branch_name: true                  # 根据分支名添加标签
      by_files_changed: true                # 根据文件变化添加标签
      by_pr_title: true                     # 根据 PR 标题添加标签
      
    # 检查列表
    checklist:
      enabled: true
      items:
        - "代码已本地测试"
        - "添加了必要的测试"
        - "更新了相关文档"
        - "遵循了代码规范"
        
  # 过期分支处理
  stale_branch:
    enabled: true
    check_interval: daily
    actions:
      warning:                              # 警告阶段
        after_days: 21
        comment: "⚠️ 这个分支已经 {days} 天没有活动了"
        label: "stale"
      close:                                # 关闭阶段
        after_days: 60
        comment: "🔒 分支因长期不活动而关闭"
        close_pr: true
        delete_branch: false                # 不自动删除，手动确认
        
  # 清理已合并分支
  cleanup:
    enabled: true
    delete_merged_branches: true
    keep_branches: []                       # 保留的分支模式
    run_schedule: "0 0 * * 0"              # 每周日凌晨运行