# Main 分支保护规则
# 最严格的保护，用于生产代码
name: main
pattern: main  # 也可以是 main|master 支持多个

protection_rules:
  # ==================
  # Pull Request 设置
  # ==================
  require_pull_request_reviews:
    required_approving_review_count: 2      # 需要 2 个审核
    dismiss_stale_reviews: true              # 新提交时取消旧审核
    require_code_owner_reviews: true        # 需要代码所有者审核
    require_last_push_approval: false       # 最后推送者不能审核自己的代码
    dismissal_restrictions:                 # 谁可以取消审核
      users: []
      teams: ["maintainers"]
      apps: []

  # ==================
  # 状态检查
  # ==================
  required_status_checks:
    strict: true                             # 必须基于最新的主分支
    contexts:                                # 必须通过的检查
      # 测试
      - "continuous-integration/test"
      - "continuous-integration/test-unit"
      - "continuous-integration/test-integration"
      - "continuous-integration/test-e2e"
      # 代码质量
      - "continuous-integration/lint"
      - "continuous-integration/typecheck"
      - "continuous-integration/build"
      # 安全
      - "security/dependency-check"
      - "security/secrets-scan"
      - "security/codeql"
      # 版本管理
      - "changeset-bot"
      # 覆盖率
      - "codecov/patch"
      - "codecov/project"

  # ==================
  # 合并设置
  # ==================
  require_linear_history: true               # 要求线性历史（禁止 merge commit）
  allow_squash_merge: true                   # 允许 squash 合并
  allow_merge_commit: false                  # 禁止 merge commit
  allow_rebase_merge: false                  # 禁止 rebase 合并
  allow_auto_merge: true                     # 允许自动合并
  delete_branch_on_merge: true               # 合并后删除分支
  
  # ==================
  # 推送限制
  # ==================
  restrict_pushes:
    enforce_admins: false                    # 管理员也要遵守规则
    push_restrictions:                       # 谁可以推送
      users: []
      teams: ["maintainers", "release-bot"]
      apps: ["github-actions[bot]"]
  
  # ==================
  # 其他保护
  # ==================
  allow_force_pushes: false                  # 禁止强制推送
  allow_deletions: false                     # 禁止删除分支
  lock_branch: false                         # 锁定分支（只读）
  require_conversation_resolution: true      # 必须解决所有对话
  require_deployments: false                 # 需要部署成功
  
# ==================
# 自动化规则
# ==================
automation:
  # 自动合并
  auto_merge:
    enabled: true
    allowed_merge_methods: ["squash"]
    conditions:
      - all_checks_passed: true
      - approvals_count: ">= 2"
      - labels_include: ["ready-to-merge"]
      - labels_exclude: ["do-not-merge", "wip"]
  
  # 标签管理
  auto_label:
    size_labels:                            # 根据改动大小
      XS: { max: 10 }
      S: { max: 50 }
      M: { max: 200 }
      L: { max: 500 }
      XL: { min: 500 }
    
    path_labels:                            # 根据文件路径
      frontend: ["src/**", "*.tsx", "*.jsx"]
      backend: ["api/**", "server/**"]
      docs: ["docs/**", "*.md"]
      tests: ["**/*.test.*", "**/*.spec.*"]
      
  # 通知设置
  notifications:
    slack:
      enabled: true
      webhook_url: "${SLACK_WEBHOOK_URL}"
      events:
        - merge_to_main
        - deployment_success
        - deployment_failure