name: PR Command

on:
  issue_comment:
    types: [created]

jobs:
  create-pr:
    if: |
      github.event.issue.pull_request == null &&
      startsWith(github.event.comment.body, '/pr')
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Parse command
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            console.log('Parsing command:', comment);
            
            // Extract parameters using regex
            const sourceMatch = comment.match(/--source\s+([^\s]+)/);
            const targetMatch = comment.match(/--target\s+([^\s]+)/);
            const titleMatch = comment.match(/--title\s+"([^"]+)"/);
            const contentMatch = comment.match(/--content\s+"([^"]+)"/);
            const draftMatch = comment.match(/--draft/);
            
            // Set outputs
            core.setOutput('source', sourceMatch ? sourceMatch[1] : '');
            core.setOutput('target', targetMatch ? targetMatch[1] : '');
            core.setOutput('title', titleMatch ? titleMatch[1] : '');
            core.setOutput('content', contentMatch ? contentMatch[1] : '');
            core.setOutput('draft', draftMatch ? 'true' : 'false');
            
            console.log('Parsed parameters:');
            console.log(`  source: ${sourceMatch ? sourceMatch[1] : 'auto-detect'}`);
            console.log(`  target: ${targetMatch ? targetMatch[1] : 'auto-detect'}`);
            console.log(`  title: ${titleMatch ? titleMatch[1] : 'auto-generate'}`);
            console.log(`  content: ${contentMatch ? contentMatch[1] : 'auto-generate'}`);
            console.log(`  draft: ${draftMatch ? 'true' : 'false'}`);
            
      - name: Get issue details
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            
            // Get issue details
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            
            core.setOutput('number', issueNumber);
            core.setOutput('title', issue.title);
            core.setOutput('body', issue.body || '');
            
            // Extract labels
            const labels = issue.labels.map(l => l.name);
            core.setOutput('labels', labels.join(','));
            
            console.log(`Issue #${issueNumber}: ${issue.title}`);
            return issue;
            
      - name: Detect source branch
        id: source
        run: |
          SOURCE="${{ steps.parse.outputs.source }}"
          ISSUE_NUMBER="${{ steps.issue.outputs.number }}"
          
          if [ -n "$SOURCE" ]; then
            echo "Using specified source branch: $SOURCE"
            # Verify branch exists
            if ! git show-ref --verify --quiet "refs/remotes/origin/$SOURCE"; then
              echo "❌ Source branch '$SOURCE' does not exist"
              exit 1
            fi
          else
            echo "Auto-detecting source branch for issue #$ISSUE_NUMBER"
            
            # List all remote branches
            git fetch origin
            BRANCHES=$(git branch -r | sed 's/origin\///' | grep -v HEAD)
            
            # Look for branches matching the issue number
            PATTERNS=(
              "feature/#${ISSUE_NUMBER}-"
              "fix/#${ISSUE_NUMBER}-"
              "docs/#${ISSUE_NUMBER}-"
              "chore/#${ISSUE_NUMBER}-"
            )
            
            for PATTERN in "${PATTERNS[@]}"; do
              for BRANCH in $BRANCHES; do
                if [[ "$BRANCH" == *"$PATTERN"* ]]; then
                  SOURCE="$BRANCH"
                  echo "Found matching branch: $SOURCE"
                  break 2
                fi
              done
            done
            
            if [ -z "$SOURCE" ]; then
              echo "❌ Could not find a branch for issue #$ISSUE_NUMBER"
              echo "Please specify source branch using --source parameter"
              exit 1
            fi
          fi
          
          echo "source=$SOURCE" >> $GITHUB_OUTPUT
          
      - name: Detect target branch
        id: target
        run: |
          TARGET="${{ steps.parse.outputs.target }}"
          SOURCE="${{ steps.source.outputs.source }}"
          
          if [ -n "$TARGET" ]; then
            echo "Using specified target branch: $TARGET"
            # Verify branch exists
            if ! git show-ref --verify --quiet "refs/remotes/origin/$TARGET"; then
              echo "❌ Target branch '$TARGET' does not exist"
              exit 1
            fi
          else
            echo "Auto-detecting target branch based on source: $SOURCE"
            
            # Get all branches
            BRANCHES=$(git branch -r | sed 's/origin\///' | grep -v HEAD)
            
            # Determine target based on source branch type
            if [[ "$SOURCE" == feature/* ]]; then
              # Features go to develop/dev/main
              for CANDIDATE in develop dev main master; do
                if echo "$BRANCHES" | grep -q "^$CANDIDATE$"; then
                  TARGET="$CANDIDATE"
                  break
                fi
              done
            elif [[ "$SOURCE" == fix/* ]] || [[ "$SOURCE" == hotfix/* ]]; then
              # Fixes go to main/master
              for CANDIDATE in main master; do
                if echo "$BRANCHES" | grep -q "^$CANDIDATE$"; then
                  TARGET="$CANDIDATE"
                  break
                fi
              done
            elif [[ "$SOURCE" == docs/* ]] || [[ "$SOURCE" == chore/* ]]; then
              # Docs and chores go to main/master
              for CANDIDATE in main master; do
                if echo "$BRANCHES" | grep -q "^$CANDIDATE$"; then
                  TARGET="$CANDIDATE"
                  break
                fi
              done
            fi
            
            # Fallback to default branch if not determined
            if [ -z "$TARGET" ]; then
              TARGET=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
              echo "Using default branch: $TARGET"
            fi
          fi
          
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          
      - name: Generate PR content
        id: content
        uses: actions/github-script@v7
        with:
          script: |
            const source = '${{ steps.source.outputs.source }}';
            const target = '${{ steps.target.outputs.target }}';
            const issueNumber = '${{ steps.issue.outputs.number }}';
            const issueTitle = `${{ steps.issue.outputs.title }}`;
            const issueBody = `${{ steps.issue.outputs.body }}`;
            const customTitle = `${{ steps.parse.outputs.title }}`;
            const customContent = `${{ steps.parse.outputs.content }}`;
            
            // Generate PR title
            let prTitle = customTitle;
            if (!prTitle) {
              // Auto-generate from issue title
              const typePrefix = source.split('/')[0];
              const typeMap = {
                'feature': 'feat',
                'fix': 'fix',
                'docs': 'docs',
                'chore': 'chore'
              };
              const prefix = typeMap[typePrefix] || 'feat';
              prTitle = `${prefix}: ${issueTitle}`;
            }
            
            // Generate PR body
            let prBody = customContent;
            if (!prBody) {
              // Auto-generate content
              prBody = `## 📋 概述\n${issueTitle}\n\n`;
              prBody += `## 🔗 关联 Issue\nCloses #${issueNumber}\n\n`;
              
              if (issueBody) {
                // Add issue description summary
                const summary = issueBody.split('\n').slice(0, 5).join('\n');
                prBody += `## 📝 描述\n${summary}\n\n`;
              }
              
              // Get commit messages between branches
              prBody += `## ✅ 提交记录\n`;
              prBody += `查看 [提交历史](https://github.com/${context.repo.owner}/${context.repo.repo}/compare/${target}...${source})\n\n`;
              
              prBody += `## 🧪 测试清单\n`;
              prBody += `- [ ] 代码已自测\n`;
              prBody += `- [ ] 相关测试已通过\n`;
              prBody += `- [ ] 文档已更新（如需要）\n\n`;
              
              prBody += `---\n`;
              prBody += `*此 PR 由 /pr 命令自动创建*`;
            }
            
            core.setOutput('title', prTitle);
            core.setOutput('body', prBody);
            
            console.log('Generated PR title:', prTitle);
            console.log('Generated PR body:', prBody.substring(0, 200) + '...');
            
      - name: Get commits between branches
        id: commits
        run: |
          SOURCE="${{ steps.source.outputs.source }}"
          TARGET="${{ steps.target.outputs.target }}"
          
          echo "Getting commits from $TARGET to $SOURCE"
          
          # Get commit count
          COMMIT_COUNT=$(git rev-list --count origin/$TARGET..origin/$SOURCE 2>/dev/null || echo "0")
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$COMMIT_COUNT" -eq "0" ]; then
            echo "⚠️ No new commits found between $TARGET and $SOURCE"
          else
            echo "Found $COMMIT_COUNT new commits"
            
            # Get commit messages
            COMMITS=$(git log --oneline origin/$TARGET..origin/$SOURCE 2>/dev/null | head -10 || echo "")
            echo "commits<<EOF" >> $GITHUB_OUTPUT
            echo "$COMMITS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
      - name: Create pull request
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const source = '${{ steps.source.outputs.source }}';
            const target = '${{ steps.target.outputs.target }}';
            const title = `${{ steps.content.outputs.title }}`;
            const body = `${{ steps.content.outputs.body }}`;
            const draft = '${{ steps.parse.outputs.draft }}' === 'true';
            const issueNumber = '${{ steps.issue.outputs.number }}';
            const labels = '${{ steps.issue.outputs.labels }}'.split(',').filter(l => l);
            const commitCount = '${{ steps.commits.outputs.commit_count }}';
            
            // Check if PR already exists
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${source}`,
              base: target,
              state: 'open'
            });
            
            if (pulls.length > 0) {
              const existingPR = pulls[0];
              console.log(`PR already exists: #${existingPR.number}`);
              core.setOutput('number', existingPR.number);
              core.setOutput('url', existingPR.html_url);
              core.setOutput('exists', 'true');
              return existingPR;
            }
            
            // Check commit count
            if (commitCount === '0') {
              core.setFailed(`No commits to create PR from ${source} to ${target}`);
              return;
            }
            
            // Create new PR
            try {
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                head: source,
                base: target,
                draft: draft
              });
              
              console.log(`Created PR #${pr.number}`);
              core.setOutput('number', pr.number);
              core.setOutput('url', pr.html_url);
              core.setOutput('exists', 'false');
              
              // Add labels if any
              if (labels.length > 0) {
                try {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    labels: labels
                  });
                  console.log('Added labels:', labels.join(', '));
                } catch (e) {
                  console.log('Failed to add labels:', e.message);
                }
              }
              
              // Add assignee
              try {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  assignees: [context.payload.comment.user.login]
                });
              } catch (e) {
                console.log('Failed to add assignee:', e.message);
              }
              
              return pr;
            } catch (error) {
              console.error('Failed to create PR:', error);
              core.setFailed(`Failed to create PR: ${error.message}`);
            }
            
      - name: Comment result
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ job.status }}' === 'success';
            const prNumber = '${{ steps.pr.outputs.number }}';
            const prUrl = '${{ steps.pr.outputs.url }}';
            const prExists = '${{ steps.pr.outputs.exists }}' === 'true';
            const source = '${{ steps.source.outputs.source }}';
            const target = '${{ steps.target.outputs.target }}';
            const draft = '${{ steps.parse.outputs.draft }}' === 'true';
            
            let message;
            
            if (success && prNumber) {
              if (prExists) {
                message = `### ⚠️ Pull Request 已存在\n\n`;
                message += `**PR**: #${prNumber}\n`;
                message += `**链接**: ${prUrl}\n`;
                message += `**分支**: \`${source}\` → \`${target}\`\n`;
              } else {
                const icon = draft ? '📝' : '✅';
                const status = draft ? '草稿 PR' : 'Pull Request';
                message = `### ${icon} ${status} 创建成功！\n\n`;
                message += `**PR**: #${prNumber}\n`;
                message += `**链接**: ${prUrl}\n`;
                message += `**源分支**: \`${source}\`\n`;
                message += `**目标分支**: \`${target}\`\n`;
                
                if (draft) {
                  message += `\n⚠️ 这是一个草稿 PR，完成开发后请点击 "Ready for review" 按钮。`;
                } else {
                  message += `\n✅ PR 已准备好接受审查。`;
                }
                
                message += `\n\n### 后续步骤\n`;
                message += `1. 等待 CI 检查通过\n`;
                message += `2. 请求代码审查\n`;
                message += `3. 合并到 \`${target}\` 分支\n`;
              }
            } else {
              message = `### ❌ 创建 Pull Request 失败\n\n`;
              
              // Add error details based on what failed
              const commitCount = '${{ steps.commits.outputs.commit_count }}';
              if (commitCount === '0') {
                message += `**原因**: \`${source}\` 和 \`${target}\` 之间没有新的提交\n\n`;
                message += `请确保：\n`;
                message += `1. 源分支有新的提交\n`;
                message += `2. 源分支已推送到远程仓库\n`;
              } else if (!source) {
                message += `**原因**: 无法检测源分支\n\n`;
                message += `请使用 \`--source\` 参数指定源分支：\n`;
                message += `\`\`\`\n/pr --source feature/#${context.issue.number}-xxx\n\`\`\``;
              } else {
                message += `请查看 [工作流日志](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) 了解详情。`;
              }
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });